syntax = "proto3";

package api;
option go_package = "./api";
service TaskManager {
    rpc RegisterAgent(AgentDetails) returns (AgentDetails);
    rpc ListAgents(Empty) returns (AgentList);
    rpc ScheduleTask(NewTask) returns (Empty);
    rpc NextTask(AgentIdentity) returns (TaskDetails);
    rpc AppendLog(LogEntry) returns (Empty);
}

message AgentList {
    repeated AgentDetails agent = 1;
}

message NewTask {
    AgentIdentity identity = 1;
    int64 timeout_seconds = 2;
    string instructions = 3;
    repeated KeyValue fields = 4;
}

message AgentDetails {
    AgentIdentity identity = 1;
    string name = 2;
    repeated string executors = 3;
    int32 maxConcurrent = 4;
}

message AgentIdentity {
    string id = 1;
}

message TaskDetails {
    string task_id = 1;
    string executor = 2;
    string access_token = 3;
    int64 timeout_seconds = 4;
    string instructions = 5;
    repeated KeyValue fields = 6;
}

message Empty {}

message LogEntry {
    string task_id = 1;
    repeated string stdout = 2;
    repeated string stderr = 3;
    repeated KeyValue fields = 4;
}

message KeyValue {
    string key = 1;
    repeated string values = 2;
}
